### ISSUE TITLE
e2 Studio Instalation

### ISSUE THREAD

**Issue by VictorAlvaradoDSE** [JosueUribe/M4_DCMVC#1]
Install the e2 Studio Software development

**Comment by VictorAlvaradoDSE** [comment]
For yesterday

**Comment by JosueUribe** [comment]
Implemented

**Comment by VictorAlvaradoDSE** [comment]
Please, complete all the activities before changing to complete

*Basic project creation
*IDE configuration
*Get familiar with e2 environment

PM: Victor A.

**Comment by VictorAlvaradoDSE** [comment]
Created a c project Executable
compiler: GCCArmEmbedded
